services:
  function-calling-postgres:
    image: localhost:5005/postgres-pgvector
    container_name: function-calling-postgres
    networks:
      function-calling-network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - function-calling:/var/lib/postgresql/embedding
    ports:
      - "5401:5432"
volumes:
  function-calling:
networks:
  function-calling-network:
